# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set up Python 3.9 🐍
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # see docs https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade build
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m build
          twine upload dist/*
